export const colors = {
  dark_sky_blue: '#97C0CE',
  neutral_blue: '#5790BD',
  anti_flash_white: '#EDEFFA',
  white: '#ffffff',
  black: 'rgba(0,0,0,0.7)',
  disabled_gray: '#ccc',
  configWhite: '#fefefe',
  transparentWhite: 'rgba(255, 255, 255, 0.9)',
  columbia_blue: '#c0d9e1',
  simple_red: '#D21D26',
  cardinal_red: '#9B365E',
  bold_orange: '#F76B0E',
  ultra_yellow: '#F5D20D',
  gold_yellow: '#DFB014',
  light_green: '#90EE90',
  simple_green: '#09A63D',
  light_blue: '#ADD8E6',
  super_blue: '#0647D4',
  navy_blue: '#2D2363 ',
  simple_purple: '#74249F',
}

export const presetColors = [
  colors.cardinal_red,
  colors.simple_red,
  colors.bold_orange,
  colors.ultra_yellow,
  colors.gold_yellow,
  colors.light_green,
  colors.simple_green,
  colors.light_blue,
  colors.super_blue,
  colors.navy_blue,
  colors.simple_purple,
]
