services:
  nginx:
    image: 'nginx:latest'
    ports:
      - 443:443
      - 80:80
    volumes:
      # Save your cert and key in the application root as default.crt and default.key
      - ./default.crt:/etc/ssl/certs/nginx/default.crt:ro
      - ./default.key:/etc/ssl/certs/nginx/default.key:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app
    networks:
      - default
      - app-tier
  node-app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongodb
    env_file: .env
    networks:
      - app-tier
  mongodb:
    image: mongo:5
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - app-tier
networks:
  default:
    driver: bridge
  app-tier:
volumes:
  mongodb:
    name: dpdash-mongodb
