version: '3.8'

services:
  node-app:
    build:
      dockerfile: dev.server.Dockerfile
    depends_on:
      - mongodb
    env_file:
      - .env.development
    ports:
      - $SERVER_PORT:$SERVER_PORT
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_ADMIN_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ADMIN_PASSWORD
    volumes:
      - /data/db
