export const SITE_NAMES = {
    ME: 'Melbourne',
    CG: 'Cologne',
    JE: 'Jena',
    CP: 'Copenhagen',
    BM: 'Birmingham',
    ST: 'Santiago',
    LS: 'Lausanne',
    GW: 'Gwangju',
    SG: 'Singapore',
    HK: 'Hong Kong',
    LA: 'UCLA',
    OR: 'OREGON',
    BI: 'Harvard/BIDMC',
    NL: 'NORTHWELL',
    NC: 'UNC',
    SD: 'UCSD',
    CA: 'Calgary',
    YA: 'YALE',
    SF: 'UCSF/Path',
    PA: 'Penn',
    SI: 'Mt.Sinai',
    PI: 'Pitt',
    NN: 'Northwestern',
    IR: 'UC Irvine',
    TE: 'Temple',
    GA: 'Georgia',
    WU: 'WashU',
    HA: 'Hartford',
    MT: 'Montreal',
    KC: "King's College",
    PV: 'Pavia',
    MA: 'Madrid',
    CM: 'Cambridge UK',
    MU: 'LMU Munich',
    SH: 'Shanghai',
    SL: 'Seoul',
    OH: 'Ohio State U',
    UR: 'U of Rochester',
    CU: 'Columbia U'
}
